// Generated by an LLM

#include <libimobiledevice/libimobiledevice.h>
#include <libimobiledevice/lockdown.h>
#include <plist/plist.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>

#define DOMAIN "com.apple.mobile.wireless_lockdown"
#define KEY "EnableWifiConnections"

static int parse_state(const char *s, int *out) {
  static const char *yes[] = {"on", "true", "1", "yes", "enable", NULL};
  static const char *no[] = {"off", "false", "0", "no", "disable", NULL};

  for (int i = 0; yes[i]; i++)
    if (!strcasecmp(s, yes[i])) {
      *out = 1;
      return 0;
    }
  for (int i = 0; no[i]; i++)
    if (!strcasecmp(s, no[i])) {
      *out = 0;
      return 0;
    }
  return -1;
}

static void usage(const char *prog) {
  fprintf(stderr,
          "usage: %s [--udid UDID] [on|off|true|false|1|0]\n"
          "  --udid, -u   target device; default is the first device found\n"
          "  no state     print the current value\n",
          prog);
}

int main(int argc, char **argv) {
  const char *udid = NULL;
  const char *arg = NULL;
  int state = 0;

  for (int i = 1; i < argc; i++) {
    if (!strcmp(argv[i], "--udid") || !strcmp(argv[i], "-u")) {
      if (++i >= argc) {
        usage(argv[0]);
        return 2;
      }
      udid = argv[i];
    } else if (!strncmp(argv[i], "--udid=", 7)) {
      udid = argv[i] + 7;
    } else if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
      usage(argv[0]);
      return 0;
    } else if (!arg) {
      arg = argv[i];
    } else {
      usage(argv[0]);
      return 2;
    }
  }

  if (arg && parse_state(arg, &state) != 0) {
    usage(argv[0]);
    return 2;
  }

  idevice_t dev = NULL;
  lockdownd_client_t ld = NULL;

  idevice_error_t derr =
      idevice_new_with_options(&dev, udid, IDEVICE_LOOKUP_USBMUX);
  if (derr != IDEVICE_E_SUCCESS) {
    fprintf(stderr, "no usb iOS device%s%s found (error %d)\n", udid ? " with udid " : "",
            udid ? udid : "", derr);
    return 1;
  }

  lockdownd_error_t lerr =
      lockdownd_client_new_with_handshake(dev, &ld, "wifi-enable");
  if (lerr != LOCKDOWN_E_SUCCESS) {
    fprintf(stderr, "lockdown handshake: %s\n", lockdownd_strerror(lerr));
    idevice_free(dev);
    return 1;
  }

  int rc = 1;

  if (arg) {
    lerr = lockdownd_set_value(ld, DOMAIN, KEY, plist_new_bool(state));
    if (lerr == LOCKDOWN_E_SUCCESS) {
      printf("%s = %s\n", KEY, state ? "true" : "false");
      rc = 0;
    } else {
      fprintf(stderr, "set value: %s\n", lockdownd_strerror(lerr));
    }
  } else {
    plist_t node = NULL;
    lerr = lockdownd_get_value(ld, DOMAIN, KEY, &node);
    if (lerr != LOCKDOWN_E_SUCCESS) {
      fprintf(stderr, "get value: %s\n", lockdownd_strerror(lerr));
    } else if (plist_get_node_type(node) != PLIST_BOOLEAN) {
      fprintf(stderr, "%s: not set or not a boolean\n", KEY);
    } else {
      uint8_t b = 0;
      plist_get_bool_val(node, &b);
      printf("%s = %s\n", KEY, b ? "true" : "false");
      rc = 0;
    }
    plist_free(node);
  }

  lockdownd_client_free(ld);
  idevice_free(dev);
  return rc;
}
